name: 'my_alarms'
description: 'Mes Alarmes'
publish_to: 'none'
version: 0.0.6+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  crypto: ^3.0.3
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_i18n: ^0.35.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  motion_tab_bar: ^2.0.4
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  responsive_grid: ^2.4.4
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  geolocator: ^13.0.1
  local_auth: ^2.2.0
  alarm: ^4.1.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/musics/
